import numpy as np
import util
import widget_bot as wb

class Meal:
    def __init__(self, data):
        self.data = data
        self.id = self.data["id"]
        self.title = self.data["title"]
        self.image = self.data["image"]
        self.restrictions = self.data["diets"] # verify
        self.nutrition = self.parse_nutrition(self.data["nutrition"]["nutrients"])
        self.ingredients = self.parse_ingredients(self.data["nutrition"]["ingredients"])
        self.categories = [each.lower() for each in self.data["dishTypes"]]
        self.cuisines = [each.lower() for each in self.data["cuisines"]]
        self.time = self.data["readyInMinutes"]
        self.servings = self.data["servings"]

    def parse_nutrition(self, nutrients):
        temp = {}
        for i in range(len(nutrients)):
            temp[nutrients[i]["name"].lower()] = nutrients[i]["percentOfDailyNeeds"]
        return [temp.get(util.NUTRIENTS_LIST[i], 0) for i in range(len(util.NUTRIENTS_LIST))]
  	
    def parse_ingredients(self, ingredients):
        return [(ingredient["id"], ingredient["amount"]) for ingredient in ingredients]

class MealPlan:

    def __init__(self, meals, mealTypes, restrictions):
        
        self.meals = [Meal(meal) for meal in meals]


    def variety_cost(self):
        counts = {}
        for meal in self.meals:
            if meal.id in counts:
                counts[meal.id] += 1
            else:
                counts[meal.id] = 1

        max_count = 0
        for count in counts.values():
            if count > util.COUNT_THRESHOLD:
                return util.VARIETY_COST
            if count > max_count:
                max_count = count

        return 0
  
    def time_cost(self):
        ids = set()
        time = 0

        # TODO: store bought meals don't have saved time cost
        for meal in self.meals:
            if meal.id not in ids:
                time += meal.time
                ids.add(meal)

        return time

    def preference_cost(self, preferences):
        aggregate = {}
        for meal in self.meals:
            for cuisine in meal.cuisines:
                aggregate[cuisine] = aggregate.get(cuisine, 0) + 1
        
        cost = 0
        for cuisine in preferences:
            cost -= aggregate.get(cuisine, 0) * preferences[cuisine]
        return cost

    def ingredient_cost(self, ingredients):
        aggregate = {}
        for meal in self.meals:
            for ingredient in meal.ingredients:
                aggregate[ingredient[0]] = aggregate.get(ingredient[0], 0) + ingredient[1]

        cost = 0
        for _id in aggregate:
            cost += max(0, aggregate[_id] - ingredients.get(_id, 0)) / aggregate[_id]
        return cost

    def nutrition_cost(self, dv):
        return np.sqrt(np.sum(util.NUTRITION_WEIGHTS * (sum([np.array(meal.nutrition) for meal in self.meals]) - np.array(dv)) ** 2))

    def total_cost(self, preferences, ingredients, dv):
        return np.dot(np.array([self.variety_cost(), self.time_cost(), self.preference_cost(preferences), self.ingredient_cost(ingredients), self.nutrition_cost(dv)]), util.COST_WEIGHTS)

class User:
    # demographics: age, gender, height, weight, exercise
    # goals: gain weight, lose weight, gain muscle
    # restrictions: restrictions
    # preferences: cuisines
    # meal types: breakfast, lunch, dinner
    # restaurants: location, radius, outside meals per week
    # ingredients: home ingredients

    _demographics = []
    _goals = []
    _restrictions = []
    _preferences = {}
    _meal_types = []
    _restaurants = []
    _ingredients = {}
    dv = []

    def __init__(self, demographics, goals, restrictions, preferences, meal_types, restaurants, ingredients):
        User._demographics = demographics # age, gender, activity, weight, height_ft, height_in
        User._goals = goals
        User._restrictions = restrictions
        User._preferences = preferences
        User._meal_types = meal_types
        User._restaurants = restaurants
        User._ingredients = ingredients

    @classmethod
    def calculate_calories(cls):
        # scraping work
        link = wb.open(*User._demographics)
        return int(link.split('/')[-1].split('-')[0])

    @classmethod
    def calculate_goal_dv(cls):
        calories = User.calculate_calories() + 200 * User._goals[0] - 200 * User._goals[1]
        User.dv = np.array([1.0] * len(util.NUTRIENTS_LIST)) * (calories / 2000)
        User.dv[-1] += 0.3 * User._goals[2]




'''
{'vegetarian': True,
 'vegan': False,
 'glutenFree': False,
 'dairyFree': False,
 'veryHealthy': True,
 'cheap': False,
 'veryPopular': True,
 'sustainable': False,
 'lowFodmap': False,
 'weightWatcherSmartPoints': 15,
 'gaps': 'no',
 'preparationMinutes': 5,
 'cookingMinutes': 0,
 'aggregateLikes': 689,
 'healthScore': 64,
 'creditsText': 'Jen West',
 'sourceName': 'Pink When',
 'pricePerServing': 206.79,
 'id': 715497,
 'title': 'Berry Banana Breakfast Smoothie',
 'readyInMinutes': 5,
 'servings': 1,
 'sourceUrl': 'http://www.pinkwhen.com/berry-banana-breakfast-smoothie/',
 'image': 'https://spoonacular.com/recipeImages/715497-312x231.jpg',
 'imageType': 'jpg',
 'nutrition': {'nutrients': [{'name': 'Calories',
    'amount': 457.05,
    'unit': 'kcal',
    'percentOfDailyNeeds': 22.85},
   {'name': 'Fat', 'amount': 9.94, 'unit': 'g', 'percentOfDailyNeeds': 15.29},
   {'name': 'Saturated Fat',
    'amount': 2.7,
    'unit': 'g',
    'percentOfDailyNeeds': 16.88},
   {'name': 'Carbohydrates',
    'amount': 73.06,
    'unit': 'g',
    'percentOfDailyNeeds': 24.35},
   {'name': 'Net Carbohydrates',
    'amount': 68.54,
    'unit': 'g',
    'percentOfDailyNeeds': 24.92},
   {'name': 'Sugar',
    'amount': 52.28,
    'unit': 'g',
    'percentOfDailyNeeds': 58.09},
   {'name': 'Cholesterol',
    'amount': 11.35,
    'unit': 'mg',
    'percentOfDailyNeeds': 3.78},
   {'name': 'Sodium',
    'amount': 400.9,
    'unit': 'mg',
    'percentOfDailyNeeds': 17.43},
   {'name': 'Protein',
    'amount': 20.62,
    'unit': 'g',
    'percentOfDailyNeeds': 41.25},
   {'name': 'Vitamin C',
    'amount': 66.04,
    'unit': 'mg',
    'percentOfDailyNeeds': 80.05},
   {'name': 'Calcium',
    'amount': 748.7,
    'unit': 'mg',
    'percentOfDailyNeeds': 74.87},
   {'name': 'Vitamin B12',
    'amount': 3.75,
    'unit': 'µg',
    'percentOfDailyNeeds': 62.53},
   {'name': 'Vitamin B2',
    'amount': 1.03,
    'unit': 'mg',
    'percentOfDailyNeeds': 60.64},
   {'name': 'Vitamin B3',
    'amount': 9.42,
    'unit': 'mg',
    'percentOfDailyNeeds': 47.1},
   {'name': 'Vitamin B6',
    'amount': 0.91,
    'unit': 'mg',
    'percentOfDailyNeeds': 45.62},
   {'name': 'Vitamin E',
    'amount': 6.26,
    'unit': 'mg',
    'percentOfDailyNeeds': 41.72},
   {'name': 'Phosphorus',
    'amount': 376.51,
    'unit': 'mg',
    'percentOfDailyNeeds': 37.65},
   {'name': 'Folate',
    'amount': 138.22,
    'unit': 'µg',
    'percentOfDailyNeeds': 34.56},
   {'name': 'Potassium',
    'amount': 1176.83,
    'unit': 'mg',
    'percentOfDailyNeeds': 33.62},
   {'name': 'Selenium',
    'amount': 17.4,
    'unit': 'µg',
    'percentOfDailyNeeds': 24.86},
   {'name': 'Manganese',
    'amount': 0.44,
    'unit': 'mg',
    'percentOfDailyNeeds': 21.94},
   {'name': 'Vitamin B1',
    'amount': 0.32,
    'unit': 'mg',
    'percentOfDailyNeeds': 21.47},
   {'name': 'Vitamin A',
    'amount': 1069.73,
    'unit': 'IU',
    'percentOfDailyNeeds': 21.39},
   {'name': 'Copper',
    'amount': 0.4,
    'unit': 'mg',
    'percentOfDailyNeeds': 20.21},
   {'name': 'Zinc',
    'amount': 3.02,
    'unit': 'mg',
    'percentOfDailyNeeds': 20.16},
   {'name': 'Vitamin D',
    'amount': 2.83,
    'unit': 'µg',
    'percentOfDailyNeeds': 18.88},
   {'name': 'Magnesium',
    'amount': 72.67,
    'unit': 'mg',
    'percentOfDailyNeeds': 18.17},
   {'name': 'Fiber',
    'amount': 4.53,
    'unit': 'g',
    'percentOfDailyNeeds': 18.11},
   {'name': 'Vitamin B5',
    'amount': 1.53,
    'unit': 'mg',
    'percentOfDailyNeeds': 15.31},
   {'name': 'Iron',
    'amount': 2.58,
    'unit': 'mg',
    'percentOfDailyNeeds': 14.35},
   {'name': 'Vitamin K',
    'amount': 2.09,
    'unit': 'µg',
    'percentOfDailyNeeds': 1.99}],
  'properties': [{'name': 'Glycemic Index', 'amount': 202.19, 'unit': ''},
   {'name': 'Glycemic Load', 'amount': 21.04, 'unit': ''},
   {'name': 'Inflammation Score', 'amount': -8.0, 'unit': ''},
   {'name': 'Nutrition Score', 'amount': 31.965217391304346, 'unit': '%'}],
  'flavonoids': [{'name': 'Cyanidin', 'amount': 1.21, 'unit': 'mg'},
   {'name': 'Petunidin', 'amount': 0.08, 'unit': 'mg'},
   {'name': 'Delphinidin', 'amount': 0.22, 'unit': 'mg'},
   {'name': 'Malvidin', 'amount': 0.01, 'unit': 'mg'},
   {'name': 'Pelargonidin', 'amount': 17.89, 'unit': 'mg'},
   {'name': 'Peonidin', 'amount': 0.04, 'unit': 'mg'},
   {'name': 'Catechin', 'amount': 5.67, 'unit': 'mg'},
   {'name': 'Epigallocatechin', 'amount': 0.56, 'unit': 'mg'},
   {'name': 'Epicatechin', 'amount': 0.31, 'unit': 'mg'},
   {'name': 'Epicatechin 3-gallate', 'amount': 0.11, 'unit': 'mg'},
   {'name': 'Epigallocatechin 3-gallate', 'amount': 0.08, 'unit': 'mg'},
   {'name': 'Theaflavin', 'amount': 0.0, 'unit': ''},
   {'name': 'Thearubigins', 'amount': 0.0, 'unit': ''},
   {'name': 'Eriodictyol', 'amount': 0.0, 'unit': ''},
   {'name': 'Hesperetin', 'amount': 0.0, 'unit': 'mg'},
   {'name': 'Naringenin', 'amount': 0.19, 'unit': 'mg'},
   {'name': 'Apigenin', 'amount': 0.0, 'unit': 'mg'},
   {'name': 'Luteolin', 'amount': 0.0, 'unit': 'mg'},
   {'name': 'Isorhamnetin', 'amount': 0.0, 'unit': 'mg'},
   {'name': 'Kaempferol', 'amount': 0.42, 'unit': 'mg'},
   {'name': 'Myricetin', 'amount': 0.03, 'unit': 'mg'},
   {'name': 'Quercetin', 'amount': 0.83, 'unit': 'mg'},
   {'name': "Theaflavin-3,3'-digallate", 'amount': 0.0, 'unit': ''},
   {'name': "Theaflavin-3'-gallate", 'amount': 0.0, 'unit': ''},
   {'name': 'Theaflavin-3-gallate', 'amount': 0.0, 'unit': ''},
   {'name': 'Gallocatechin', 'amount': 0.02, 'unit': 'mg'}],
  'ingredients': [{'id': 1009040,
    'name': 'banana',
    'amount': 0.25,
    'unit': 'cup',
    'nutrients': [{'name': 'Folate',
      'amount': 11.25,
      'unit': 'µg',
      'percentOfDailyNeeds': 34.56},
     {'name': 'Phosphorus',
      'amount': 12.38,
      'unit': 'mg',
      'percentOfDailyNeeds': 37.65},
     {'name': 'Vitamin B5',
      'amount': 0.19,
      'unit': 'mg',
      'percentOfDailyNeeds': 15.31},
     {'name': 'Vitamin B2',
      'amount': 0.04,
      'unit': 'mg',
      'percentOfDailyNeeds': 60.64},
     {'name': 'Poly Unsaturated Fat',
      'amount': 0.04,
      'unit': 'g',
      'percentOfDailyNeeds': 0.0},
     {'name': 'Saturated Fat',
      'amount': 0.06,
      'unit': 'g',
      'percentOfDailyNeeds': 16.88},
     {'name': 'Iron',
      'amount': 0.15,
      'unit': 'mg',
      'percentOfDailyNeeds': 14.35},
     {'name': 'Magnesium',
      'amount': 15.19,
      'unit': 'mg',
      'percentOfDailyNeeds': 18.17},
     {'name': 'Manganese',
      'amount': 0.15,
      'unit': 'mg',
      'percentOfDailyNeeds': 21.94},
     {'name': 'Vitamin C',
      'amount': 4.89,
      'unit': 'mg',
      'percentOfDailyNeeds': 80.05},
     {'name': 'Vitamin A',
      'amount': 36.0,
      'unit': 'IU',
      'percentOfDailyNeeds': 21.39},
     {'name': 'Protein',
      'amount': 0.61,
      'unit': 'g',
      'percentOfDailyNeeds': 41.25},
     {'name': 'Vitamin B3',
      'amount': 0.37,
      'unit': 'mg',
      'percentOfDailyNeeds': 47.1},
     {'name': 'Fiber',
      'amount': 1.46,
      'unit': 'g',
      'percentOfDailyNeeds': 18.11},
     {'name': 'Vitamin K',
      'amount': 0.28,
      'unit': 'µg',
      'percentOfDailyNeeds': 1.99},
     {'name': 'Carbohydrates',
      'amount': 12.82,
      'unit': 'g',
      'percentOfDailyNeeds': 24.35},
     {'name': 'Vitamin B6',
      'amount': 0.21,
      'unit': 'mg',
      'percentOfDailyNeeds': 45.62},
     {'name': 'Mono Unsaturated Fat',
      'amount': 0.02,
      'unit': 'g',
      'percentOfDailyNeeds': 0.0},
     {'name': 'Sugar',
      'amount': 6.86,
      'unit': 'g',
      'percentOfDailyNeeds': 58.09},
     {'name': 'Net Carbohydrates',
      'amount': 11.36,
      'unit': 'g',
      'percentOfDailyNeeds': 24.92},
     {'name': 'Alcohol',
      'amount': 0.0,
      'unit': 'g',
      'percentOfDailyNeeds': 0.0},
     {'name': 'Calcium',
      'amount': 2.81,
      'unit': 'mg',
      'percentOfDailyNeeds': 74.87},
     {'name': 'Zinc',
      'amount': 0.08,
      'unit': 'mg',
      'percentOfDailyNeeds': 20.16},
     {'name': 'Calories',
      'amount': 50.06,
      'unit': 'kcal',
      'percentOfDailyNeeds': 22.85},
     {'name': 'Potassium',
      'amount': 201.38,
      'unit': 'mg',
      'percentOfDailyNeeds': 33.62},
     {'name': 'Choline',
      'amount': 5.51,
      'unit': 'mg',
      'percentOfDailyNeeds': 0.0},
     {'name': 'Sodium',
      'amount': 0.56,
      'unit': 'mg',
      'percentOfDailyNeeds': 17.43},
     {'name': 'Cholesterol',
      'amount': 0.0,
      'unit': 'mg',
      'percentOfDailyNeeds': 3.78},
     {'name': 'Vitamin B1',
      'amount': 0.02,
      'unit': 'mg',
      'percentOfDailyNeeds': 21.47},
     {'name': 'Copper',
      'amount': 0.04,
      'unit': 'mg',
      'percentOfDailyNeeds': 20.21},
     {'name': 'Vitamin D',
      'amount': 0.0,
      'unit': 'µg',
      'percentOfDailyNeeds': 18.88},
     {'name': 'Fluoride',
      'amount': 1.24,
      'unit': 'mg',
      'percentOfDailyNeeds': 0.0},
     {'name': 'Lycopene',
      'amount': 0.0,
      'unit': 'µg',
      'percentOfDailyNeeds': 0.0},
     {'name': 'Selenium',
      'amount': 0.56,
      'unit': 'µg',
      'percentOfDailyNeeds': 24.86},
     {'name': 'Vitamin E',
      'amount': 0.06,
      'unit': 'mg',
      'percentOfDailyNeeds': 41.72},
     {'name': 'Folic Acid',
      'amount': 0.0,
      'unit': 'µg',
      'percentOfDailyNeeds': 0.0},
     {'name': 'Vitamin B12',
      'amount': 0.0,
      'unit': 'µg',
      'percentOfDailyNeeds': 62.53},
     {'name': 'Caffeine',
      'amount': 0.0,
      'unit': 'mg',
      'percentOfDailyNeeds': 0.0},
     {'name': 'Fat',
      'amount': 0.19,
      'unit': 'g',
      'percentOfDailyNeeds': 15.29}]},
   {'id': 10018617,
    'name': 'graham cracker crumbs',
    'amount': 2.0,
    'unit': 'tbsp',
    'nutrients': [{'name': 'Folate',
      'amount': 9.2,
      'unit': 'µg',
      'percentOfDailyNeeds': 34.56},
     {'name': 'Phosphorus',
      'amount': 40.4,
      'unit': 'mg',
      'percentOfDailyNeeds': 37.65},
     {'name': 'Vitamin B2',
      'amount': 0.05,
      'unit': 'mg',
      'percentOfDailyNeeds': 60.64},
     {'name': 'Poly Unsaturated Fat',
      'amount': 0.09,
      'unit': 'g',
      'percentOfDailyNeeds': 0.0},
     {'name': 'Iron',
      'amount': 0.83,
      'unit': 'mg',
      'percentOfDailyNeeds': 14.35},
     {'name': 'Magnesium',
      'amount': 11.8,
      'unit': 'mg',
      'percentOfDailyNeeds': 18.17},
     {'name': 'Saturated Fat',
      'amount': 0.31,
      'unit': 'g',
      'percentOfDailyNeeds': 16.88},
     {'name': 'Vitamin C',
      'amount': 0.0,
      'unit': 'mg',
      'percentOfDailyNeeds': 80.05},
     {'name': 'Vitamin A',
      'amount': 0.0,
      'unit': 'IU',
      'percentOfDailyNeeds': 21.39},
     {'name': 'Protein',
      'amount': 1.4,
      'unit': 'g',
      'percentOfDailyNeeds': 41.25},
     {'name': 'Fiber',
      'amount': 0.68,
      'unit': 'g',
      'percentOfDailyNeeds': 18.11},
     {'name': 'Vitamin B3',
      'amount': 0.76,
      'unit': 'mg',
      'percentOfDailyNeeds': 47.1},
     {'name': 'Carbohydrates',
      'amount': 15.24,
      'unit': 'g',
      'percentOfDailyNeeds': 24.35},
     {'name': 'Vitamin B6',
      'amount': 0.02,
      'unit': 'mg',
      'percentOfDailyNeeds': 45.62},
     {'name': 'Sugar',
      'amount': 4.6,
      'unit': 'g',
      'percentOfDailyNeeds': 58.09},
     {'name': 'Mono Unsaturated Fat',
      'amount': 0.72,
      'unit': 'g',
      'percentOfDailyNeeds': 0.0},
     {'name': 'Net Carbohydrates',
      'amount': 14.56,
      'unit': 'g',
      'percentOfDailyNeeds': 24.92},
     {'name': 'Calcium',
      'amount': 15.8,
      'unit': 'mg',
      'percentOfDailyNeeds': 74.87},
     {'name': 'Zinc',
      'amount': 0.39,
      'unit': 'mg',
      'percentOfDailyNeeds': 20.16},
     {'name': 'Calories',
      'amount': 84.8,
      'unit': 'kcal',
      'percentOfDailyNeeds': 22.85},
     {'name': 'Potassium',
      'amount': 35.4,
      'unit': 'mg',
      'percentOfDailyNeeds': 33.62},
     {'name': 'Sodium',
      'amount': 131.8,
      'unit': 'mg',
      'percentOfDailyNeeds': 17.43},
     {'name': 'Vitamin B1',
      'amount': 0.05,
      'unit': 'mg',
      'percentOfDailyNeeds': 21.47},
     {'name': 'Cholesterol',
      'amount': 0.0,
      'unit': 'mg',
      'percentOfDailyNeeds': 3.78},
     {'name': 'Copper',
      'amount': 0.01,
      'unit': 'mg',
      'percentOfDailyNeeds': 20.21},
     {'name': 'Fat',
      'amount': 2.0,
      'unit': 'g',
      'percentOfDailyNeeds': 15.29}]},
   {'id': 16223,
    'name': 'soy milk',
    'amount': 1.0,
    'unit': 'cup',
    'nutrients': [{'name': 'Folate',
      'amount': 75.52,
      'unit': 'µg',
      'percentOfDailyNeeds': 34.56},
     {'name': 'Vitamin B12',
      'amount': 2.55,
      'unit': 'µg',
      'percentOfDailyNeeds': 62.53},
     {'name': 'Vitamin B2',
      'amount': 0.47,
      'unit': 'mg',
      'percentOfDailyNeeds': 60.64},
     {'name': 'Poly Unsaturated Fat',
      'amount': 2.81,
      'unit': 'g',
      'percentOfDailyNeeds': 0.0},
     {'name': 'Saturated Fat',
      'amount': 0.49,
      'unit': 'g',
      'percentOfDailyNeeds': 16.88},
     {'name': 'Iron',
      'amount': 1.16,
      'unit': 'mg',
      'percentOfDailyNeeds': 14.35},
     {'name': 'Vitamin C',
      'amount': 16.99,
      'unit': 'mg',
      'percentOfDailyNeeds': 80.05},
     {'name': 'Vitamin A',
      'amount': 927.48,
      'unit': 'IU',
      'percentOfDailyNeeds': 21.39},
     {'name': 'Protein',
      'amount': 6.94,
      'unit': 'g',
      'percentOfDailyNeeds': 41.25},
     {'name': 'Fiber',
      'amount': 0.94,
      'unit': 'g',
      'percentOfDailyNeeds': 18.11},
     {'name': 'Vitamin B3',
      'amount': 7.77,
      'unit': 'mg',
      'percentOfDailyNeeds': 47.1},
     {'name': 'Trans Fat',
      'amount': 0.0,
      'unit': 'g',
      'percentOfDailyNeeds': 0.0},
     {'name': 'Carbohydrates',
      'amount': 8.14,
      'unit': 'g',
      'percentOfDailyNeeds': 24.35},
     {'name': 'Vitamin B6',
      'amount': 0.55,
      'unit': 'mg',
      'percentOfDailyNeeds': 45.62},
     {'name': 'Mono Unsaturated Fat',
      'amount': 0.97,
      'unit': 'g',
      'percentOfDailyNeeds': 0.0},
     {'name': 'Sugar',
      'amount': 5.97,
      'unit': 'g',
      'percentOfDailyNeeds': 58.09},
     {'name': 'Net Carbohydrates',
      'amount': 7.2,
      'unit': 'g',
      'percentOfDailyNeeds': 24.92},
     {'name': 'Calcium',
      'amount': 330.4,
      'unit': 'mg',
      'percentOfDailyNeeds': 74.87},
     {'name': 'Zinc',
      'amount': 0.57,
      'unit': 'mg',
      'percentOfDailyNeeds': 20.16},
     {'name': 'Calories',
      'amount': 106.2,
      'unit': 'kcal',
      'percentOfDailyNeeds': 22.85},
     {'name': 'Potassium',
      'amount': 332.76,
      'unit': 'mg',
      'percentOfDailyNeeds': 33.62},
     {'name': 'Sodium',
      'amount': 118.0,
      'unit': 'mg',
      'percentOfDailyNeeds': 17.43},
     {'name': 'Vitamin B1',
      'amount': 0.15,
      'unit': 'mg',
      'percentOfDailyNeeds': 21.47},
     {'name': 'Cholesterol',
      'amount': 0.0,
      'unit': 'mg',
      'percentOfDailyNeeds': 3.78},
     {'name': 'Copper',
      'amount': 0.29,
      'unit': 'mg',
      'percentOfDailyNeeds': 20.21},
     {'name': 'Vitamin D',
      'amount': 2.83,
      'unit': 'µg',
      'percentOfDailyNeeds': 18.88},
     {'name': 'Selenium',
      'amount': 5.43,
      'unit': 'µg',
      'percentOfDailyNeeds': 24.86},
     {'name': 'Vitamin E',
      'amount': 5.95,
      'unit': 'mg',
      'percentOfDailyNeeds': 41.72},
     {'name': 'Fat',
      'amount': 4.7,
      'unit': 'g',
      'percentOfDailyNeeds': 15.29}]},
   {'id': 9316,
    'name': 'strawberries',
    'amount': 0.5,
    'unit': 'cup',
    'nutrients': [{'name': 'Folate',
      'amount': 17.28,
      'unit': 'µg',
      'percentOfDailyNeeds': 34.56},
     {'name': 'Phosphorus',
      'amount': 17.28,
      'unit': 'mg',
      'percentOfDailyNeeds': 37.65},
     {'name': 'Vitamin B5',
      'amount': 0.09,
      'unit': 'mg',
      'percentOfDailyNeeds': 15.31},
     {'name': 'Vitamin B2',
      'amount': 0.02,
      'unit': 'mg',
      'percentOfDailyNeeds': 60.64},
     {'name': 'Poly Unsaturated Fat',
      'amount': 0.11,
      'unit': 'g',
      'percentOfDailyNeeds': 0.0},
     {'name': 'Saturated Fat',
      'amount': 0.01,
      'unit': 'g',
      'percentOfDailyNeeds': 16.88},
     {'name': 'Iron',
      'amount': 0.3,
      'unit': 'mg',
      'percentOfDailyNeeds': 14.35},
     {'name': 'Magnesium',
      'amount': 9.36,
      'unit': 'mg',
      'percentOfDailyNeeds': 18.17},
     {'name': 'Manganese',
      'amount': 0.28,
      'unit': 'mg',
      'percentOfDailyNeeds': 21.94},
     {'name': 'Vitamin C',
      'amount': 42.34,
      'unit': 'mg',
      'percentOfDailyNeeds': 80.05},
     {'name': 'Vitamin A',
      'amount': 8.64,
      'unit': 'IU',
      'percentOfDailyNeeds': 21.39},
     {'name': 'Protein',
      'amount': 0.48,
      'unit': 'g',
      'percentOfDailyNeeds': 41.25},
     {'name': 'Vitamin B3',
      'amount': 0.28,
      'unit': 'mg',
      'percentOfDailyNeeds': 47.1},
     {'name': 'Fiber',
      'amount': 1.44,
      'unit': 'g',
      'percentOfDailyNeeds': 18.11},
     {'name': 'Vitamin K',
      'amount': 1.58,
      'unit': 'µg',
      'percentOfDailyNeeds': 1.99},
     {'name': 'Carbohydrates',
      'amount': 5.53,
      'unit': 'g',
      'percentOfDailyNeeds': 24.35},
     {'name': 'Vitamin B6',
      'amount': 0.03,
      'unit': 'mg',
      'percentOfDailyNeeds': 45.62},
     {'name': 'Mono Unsaturated Fat',
      'amount': 0.03,
      'unit': 'g',
      'percentOfDailyNeeds': 0.0},
     {'name': 'Sugar',
      'amount': 3.52,
      'unit': 'g',
      'percentOfDailyNeeds': 58.09},
     {'name': 'Net Carbohydrates',
      'amount': 4.09,
      'unit': 'g',
      'percentOfDailyNeeds': 24.92},
     {'name': 'Alcohol',
      'amount': 0.0,
      'unit': 'g',
      'percentOfDailyNeeds': 0.0},
     {'name': 'Calcium',
      'amount': 11.52,
      'unit': 'mg',
      'percentOfDailyNeeds': 74.87},
     {'name': 'Zinc',
      'amount': 0.1,
      'unit': 'mg',
      'percentOfDailyNeeds': 20.16},
     {'name': 'Calories',
      'amount': 23.04,
      'unit': 'kcal',
      'percentOfDailyNeeds': 22.85},
     {'name': 'Potassium',
      'amount': 110.16,
      'unit': 'mg',
      'percentOfDailyNeeds': 33.62},
     {'name': 'Choline',
      'amount': 4.1,
      'unit': 'mg',
      'percentOfDailyNeeds': 0.0},
     {'name': 'Sodium',
      'amount': 0.72,
      'unit': 'mg',
      'percentOfDailyNeeds': 17.43},
     {'name': 'Cholesterol',
      'amount': 0.0,
      'unit': 'mg',
      'percentOfDailyNeeds': 3.78},
     {'name': 'Vitamin B1',
      'amount': 0.02,
      'unit': 'mg',
      'percentOfDailyNeeds': 21.47},
     {'name': 'Copper',
      'amount': 0.03,
      'unit': 'mg',
      'percentOfDailyNeeds': 20.21},
     {'name': 'Vitamin D',
      'amount': 0.0,
      'unit': 'µg',
      'percentOfDailyNeeds': 18.88},
     {'name': 'Fluoride',
      'amount': 3.17,
      'unit': 'mg',
      'percentOfDailyNeeds': 0.0},
     {'name': 'Lycopene',
      'amount': 0.0,
      'unit': 'µg',
      'percentOfDailyNeeds': 0.0},
     {'name': 'Selenium',
      'amount': 0.29,
      'unit': 'µg',
      'percentOfDailyNeeds': 24.86},
     {'name': 'Vitamin E',
      'amount': 0.21,
      'unit': 'mg',
      'percentOfDailyNeeds': 41.72},
     {'name': 'Folic Acid',
      'amount': 0.0,
      'unit': 'µg',
      'percentOfDailyNeeds': 0.0},
     {'name': 'Vitamin B12',
      'amount': 0.0,
      'unit': 'µg',
      'percentOfDailyNeeds': 62.53},
     {'name': 'Caffeine',
      'amount': 0.0,
      'unit': 'mg',
      'percentOfDailyNeeds': 0.0},
     {'name': 'Fat',
      'amount': 0.22,
      'unit': 'g',
      'percentOfDailyNeeds': 15.29}]},
   {'id': 1119,
    'name': 'vanilla yogurt',
    'amount': 1.0,
    'unit': 'container',
    'nutrients': [{'name': 'Folate',
      'amount': 24.97,
      'unit': 'µg',
      'percentOfDailyNeeds': 34.56},
     {'name': 'Phosphorus',
      'amount': 306.45,
      'unit': 'mg',
      'percentOfDailyNeeds': 37.65},
     {'name': 'Vitamin B5',
      'amount': 1.25,
      'unit': 'mg',
      'percentOfDailyNeeds': 15.31},
     {'name': 'Vitamin B2',
      'amount': 0.46,
      'unit': 'mg',
      'percentOfDailyNeeds': 60.64},
     {'name': 'Poly Unsaturated Fat',
      'amount': 0.08,
      'unit': 'g',
      'percentOfDailyNeeds': 0.0},
     {'name': 'Saturated Fat',
      'amount': 1.83,
      'unit': 'g',
      'percentOfDailyNeeds': 16.88},
     {'name': 'Iron',
      'amount': 0.16,
      'unit': 'mg',
      'percentOfDailyNeeds': 14.35},
     {'name': 'Magnesium',
      'amount': 36.32,
      'unit': 'mg',
      'percentOfDailyNeeds': 18.17},
     {'name': 'Manganese',
      'amount': 0.01,
      'unit': 'mg',
      'percentOfDailyNeeds': 21.94},
     {'name': 'Vitamin C',
      'amount': 1.82,
      'unit': 'mg',
      'percentOfDailyNeeds': 80.05},
     {'name': 'Vitamin A',
      'amount': 97.61,
      'unit': 'IU',
      'percentOfDailyNeeds': 21.39},
     {'name': 'Protein',
      'amount': 11.19,
      'unit': 'g',
      'percentOfDailyNeeds': 41.25},
     {'name': 'Vitamin B3',
      'amount': 0.24,
      'unit': 'mg',
      'percentOfDailyNeeds': 47.1},
     {'name': 'Fiber',
      'amount': 0.0,
      'unit': 'g',
      'percentOfDailyNeeds': 18.11},
     {'name': 'Vitamin K',
      'amount': 0.23,
      'unit': 'µg',
      'percentOfDailyNeeds': 1.99},
     {'name': 'Carbohydrates',
      'amount': 31.33,
      'unit': 'g',
      'percentOfDailyNeeds': 24.35},
     {'name': 'Vitamin B6',
      'amount': 0.1,
      'unit': 'mg',
      'percentOfDailyNeeds': 45.62},
     {'name': 'Mono Unsaturated Fat',
      'amount': 0.78,
      'unit': 'g',
      'percentOfDailyNeeds': 0.0},
     {'name': 'Sugar',
      'amount': 31.33,
      'unit': 'g',
      'percentOfDailyNeeds': 58.09},
     {'name': 'Net Carbohydrates',
      'amount': 31.33,
      'unit': 'g',
      'percentOfDailyNeeds': 24.92},
     {'name': 'Alcohol',
      'amount': 0.0,
      'unit': 'g',
      'percentOfDailyNeeds': 0.0},
     {'name': 'Calcium',
      'amount': 388.17,
      'unit': 'mg',
      'percentOfDailyNeeds': 74.87},
     {'name': 'Zinc',
      'amount': 1.88,
      'unit': 'mg',
      'percentOfDailyNeeds': 20.16},
     {'name': 'Calories',
      'amount': 192.95,
      'unit': 'kcal',
      'percentOfDailyNeeds': 22.85},
     {'name': 'Potassium',
      'amount': 497.13,
      'unit': 'mg',
      'percentOfDailyNeeds': 33.62},
     {'name': 'Choline',
      'amount': 34.5,
      'unit': 'mg',
      'percentOfDailyNeeds': 0.0},
     {'name': 'Sodium',
      'amount': 149.82,
      'unit': 'mg',
      'percentOfDailyNeeds': 17.43},
     {'name': 'Cholesterol',
      'amount': 11.35,
      'unit': 'mg',
      'percentOfDailyNeeds': 3.78},
     {'name': 'Vitamin B1',
      'amount': 0.1,
      'unit': 'mg',
      'percentOfDailyNeeds': 21.47},
     {'name': 'Copper',
      'amount': 0.03,
      'unit': 'mg',
      'percentOfDailyNeeds': 20.21},
     {'name': 'Vitamin D',
      'amount': 0.0,
      'unit': 'µg',
      'percentOfDailyNeeds': 18.88},
     {'name': 'Fluoride',
      'amount': 27.24,
      'unit': 'mg',
      'percentOfDailyNeeds': 0.0},
     {'name': 'Lycopene',
      'amount': 0.0,
      'unit': 'µg',
      'percentOfDailyNeeds': 0.0},
     {'name': 'Selenium',
      'amount': 11.12,
      'unit': 'µg',
      'percentOfDailyNeeds': 24.86},
     {'name': 'Vitamin E',
      'amount': 0.05,
      'unit': 'mg',
      'percentOfDailyNeeds': 41.72},
     {'name': 'Folic Acid',
      'amount': 0.0,
      'unit': 'µg',
      'percentOfDailyNeeds': 0.0},
     {'name': 'Vitamin B12',
      'amount': 1.2,
      'unit': 'µg',
      'percentOfDailyNeeds': 62.53},
     {'name': 'Caffeine',
      'amount': 0.0,
      'unit': 'mg',
      'percentOfDailyNeeds': 0.0},
     {'name': 'Fat',
      'amount': 2.84,
      'unit': 'g',
      'percentOfDailyNeeds': 15.29}]}],
  'caloricBreakdown': {'percentProtein': 17.77,
   'percentFat': 19.26,
   'percentCarbs': 62.97},
  'weightPerServing': {'amount': 611, 'unit': 'g'}},
 'summary': 'If you want to add more <b>lacto ovo vegetarian</b> recipes to your recipe box, Berry Banana Breakfast Smoothie might be a recipe you should try. One portion of this dish contains about <b>21g of protein</b>, <b>10g of fat</b>, and a total of <b>457 calories</b>. This recipe serves 1 and costs $2.07 per serving. 689 people have tried and liked this recipe. It works well as a rather inexpensive breakfast. A mixture of banana, graham cracker crumbs, vanilla yogurt, and a handful of other ingredients are all it takes to make this recipe so yummy. From preparation to the plate, this recipe takes roughly <b>5 minutes</b>. It is brought to you by Pink When. Overall, this recipe earns a <b>super spoonacular score of 99%</b>. Similar recipes include <a href="https://spoonacular.com/recipes/berry-banana-breakfast-smoothie-1364145">Berry Banana Breakfast Smoothie</a>, <a href="https://spoonacular.com/recipes/berry-banana-breakfast-smoothie-1405583">Berry Banana Breakfast Smoothie</a>, and <a href="https://spoonacular.com/recipes/berry-banana-breakfast-smoothie-1601311">Berry Banana Breakfast Smoothie</a>.',
 'cuisines': [],
 'dishTypes': ['morning meal', 'brunch', 'beverage', 'breakfast', 'drink'],
 'diets': ['lacto ovo vegetarian'],
 'occasions': [],
 'analyzedInstructions': [{'name': '',
   'steps': [{'number': 1,
     'step': 'Take some yogurt in your favorite flavor and add 1 container to your blender.',
     'ingredients': [{'id': 1116,
       'name': 'yogurt',
       'localizedName': 'yogurt',
       'image': 'plain-yogurt.jpg'}],
     'equipment': [{'id': 404726,
       'name': 'blender',
       'localizedName': 'blender',
       'image': 'blender.png'}]},
    {'number': 2,
     'step': 'Add in the berries, banana, and soy milk and blend. Top your glass with a few graham cracker crumbs and serve.',
     'ingredients': [{'id': 10018617,
       'name': 'graham cracker crumbs',
       'localizedName': 'graham cracker crumbs',
       'image': 'graham-crackers.jpg'},
      {'id': 16223,
       'name': 'soymilk',
       'localizedName': 'soymilk',
       'image': 'soy-milk.jpg'},
      {'id': 1009054,
       'name': 'berries',
       'localizedName': 'berries',
       'image': 'berries-mixed.jpg'},
      {'id': 9040,
       'name': 'banana',
       'localizedName': 'banana',
       'image': 'bananas.jpg'}],
     'equipment': []}]}],
 'spoonacularScore': 99.46280670166016,
 'spoonacularSourceUrl': 'https://spoonacular.com/berry-banana-breakfast-smoothie-715497'}
'''